server:
  port: 9112
  servlet:
    context-path: /api/v2
#logging:
#  config: classpath:logback-local.xml
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/diandi?serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: wd75gpH_ueWg
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: false
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        allowMultiQueries: true
      #redis配置
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        # 连接池最大连接数（使用负值表示没有限制）
        pool.max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        pool.max-wait: -1
        # 连接池中的最大空闲连接
        pool.max-idle: 8
        # 连接池中的最小空闲连接
        pool.min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 5000
    session:
        store-type: redis
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
#  config-location: classpath:mybatis-config.xml
  type-handlers-package: com.fuhaoshu.common.handler
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
transaction:
    tx_method_timeout: 60
swagger:
    host: 114.55.102.98:9112
